name: bus_stoppable_widget
description: "A minimal event stoppable widget."
version: 0.0.1
homepage: https://github.com/sudo-gugu/bus_stoppable_widget
repository: https://github.com/sudo-gugu/bus_stoppable_widget.git
license: MIT

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
